copy ..\WM2003SE\eVC4\ARMV4Rel\NaviPOWM.exe Common
copy ..\..\LICENSE.TXT Common
copy ..\..\README.TXT Common
copy ..\..\CHANGELOG.TXT Common
copy ..\..\common\Demo\demo01.txt Common
copy ..\..\common\Demo\E0071N509.map Common
copy ..\..\common\Config\navipowm.ini Common\navipowm.txt
copy ..\..\common\Images\logosmall.bmp Icons\logo.bmp
copy ..\..\common\Images\info.bmp Icons
copy ..\..\common\Images\quit.bmp Icons
copy ..\..\common\Images\saveon.bmp Icons
copy ..\..\common\Images\saveoff.bmp Icons
copy ..\..\common\Images\zoomin.bmp Icons
copy ..\..\common\Images\zoomout.bmp Icons
